# Centralized Services Configuration
# This file defines all service ports and endpoints for consistency

services:
  # Database Configuration
  postgres:
    internal_port: 5432
    external_port: 5432
    container_name: momentum_postgres
    
  # Data Service Configuration
  data_service:
    internal_port: 8001
    external_ports:
      - 8001  # data-service-1
      - 8003  # data-service-2
    container_names:
      - momentum_data_service_1
      - momentum_data_service_2
    instances:
      - name: data-service-1
        external_port: 8001
      - name: data-service-2
        external_port: 8003
        
  # Momentum Service Configuration
  momentum_service:
    internal_port: 8000
    external_port: 8000
    container_name: momentum_momentum_service
    
  # Strategy Service Configuration
  strategy_service:
    internal_port: 8002
    external_port: 8002
    container_name: momentum_strategy_service
    
  # Frontend Configuration
  frontend:
    internal_port: 3000
    external_port: 3000
    container_name: momentum_frontend
    
  # Nginx Configuration
  nginx:
    internal_port: 80
    external_port: 80
    container_name: momentum_nginx

# API Endpoints Configuration
endpoints:
  # Main API endpoints
  momentum: "/momentum"
  health: "/health"
  config: "/config"
  
  # Stock data endpoints
  stocks: "/stocks"
  sectors: "/sectors"
  industries: "/industries"
  
  # Strategy endpoints
  strategies: "/strategies"
  strategy_base: "/strategy"
  
  # Data service endpoints
  data_base: "/data"
  
  # Cache management
  cache_base: "/cache"

# CORS Configuration
cors:
  enabled: true
  allow_origin: "*"
  allow_methods: "GET, POST, OPTIONS"
  allow_headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
  expose_headers: "Content-Length,Content-Range"
  max_age: 1728000

# Load Balancing Configuration
load_balancing:
  data_service:
    enabled: true
    instances:
      - data-service-1:8001
      - data-service-2:8001
  momentum_service:
    enabled: false  # Single instance
  strategy_service:
    enabled: false  # Single instance
