"""
Comprehensive stock lists for NSE and BSE
"""

# NSE Stocks - Major companies with good liquidity
NSE_STOCKS = [
    # Large Cap Stocks
    {'symbol': 'RELIANCE', 'company_name': 'Reliance Industries Ltd', 'market_cap': 15000000, 'sector': 'Oil & Gas', 'exchange': 'NSE'},
    {'symbol': 'TCS', 'company_name': 'Tata Consultancy Services Ltd', 'market_cap': 12000000, 'sector': 'IT', 'exchange': 'NSE'},
    {'symbol': 'HDFCBANK', 'company_name': 'HDFC Bank Ltd', 'market_cap': 8000000, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'INFY', 'company_name': 'Infosys Ltd', 'market_cap': 6000000, 'sector': 'IT', 'exchange': 'NSE'},
    {'symbol': 'HINDUNILVR', 'company_name': 'Hindustan Unilever Ltd', 'market_cap': 5000000, 'sector': 'FMCG', 'exchange': 'NSE'},
    {'symbol': 'ITC', 'company_name': 'ITC Ltd', 'market_cap': 4500000, 'sector': 'FMCG', 'exchange': 'NSE'},
    {'symbol': 'KOTAKBANK', 'company_name': 'Kotak Mahindra Bank Ltd', 'market_cap': 4000000, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'BHARTIARTL', 'company_name': 'Bharti Airtel Ltd', 'market_cap': 3800000, 'sector': 'Telecom', 'exchange': 'NSE'},
    {'symbol': 'SBIN', 'company_name': 'State Bank of India', 'market_cap': 3500000, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'LT', 'company_name': 'Larsen & Toubro Ltd', 'market_cap': 3200000, 'sector': 'Engineering', 'exchange': 'NSE'},
    {'symbol': 'ASIANPAINT', 'company_name': 'Asian Paints Ltd', 'market_cap': 3000000, 'sector': 'Paints', 'exchange': 'NSE'},
    {'symbol': 'MARUTI', 'company_name': 'Maruti Suzuki India Ltd', 'market_cap': 2800000, 'sector': 'Automobile', 'exchange': 'NSE'},
    {'symbol': 'AXISBANK', 'company_name': 'Axis Bank Ltd', 'market_cap': 2600000, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'SUNPHARMA', 'company_name': 'Sun Pharmaceutical Industries Ltd', 'market_cap': 2400000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'NESTLEIND', 'company_name': 'Nestle India Ltd', 'market_cap': 2200000, 'sector': 'FMCG', 'exchange': 'NSE'},
    {'symbol': 'ULTRACEMCO', 'company_name': 'UltraTech Cement Ltd', 'market_cap': 2000000, 'sector': 'Cement', 'exchange': 'NSE'},
    {'symbol': 'TITAN', 'company_name': 'Titan Company Ltd', 'market_cap': 1800000, 'sector': 'Consumer Goods', 'exchange': 'NSE'},
    {'symbol': 'POWERGRID', 'company_name': 'Power Grid Corporation of India Ltd', 'market_cap': 1600000, 'sector': 'Power', 'exchange': 'NSE'},
    {'symbol': 'NTPC', 'company_name': 'NTPC Ltd', 'market_cap': 1400000, 'sector': 'Power', 'exchange': 'NSE'},
    {'symbol': 'ONGC', 'company_name': 'Oil and Natural Gas Corporation Ltd', 'market_cap': 1200000, 'sector': 'Oil & Gas', 'exchange': 'NSE'},
    
    # Mid Cap Stocks
    {'symbol': 'WIPRO', 'company_name': 'Wipro Ltd', 'market_cap': 1000000, 'sector': 'IT', 'exchange': 'NSE'},
    {'symbol': 'HCLTECH', 'company_name': 'HCL Technologies Ltd', 'market_cap': 900000, 'sector': 'IT', 'exchange': 'NSE'},
    {'symbol': 'TECHM', 'company_name': 'Tech Mahindra Ltd', 'market_cap': 800000, 'sector': 'IT', 'exchange': 'NSE'},
    {'symbol': 'BAJFINANCE', 'company_name': 'Bajaj Finance Ltd', 'market_cap': 700000, 'sector': 'NBFC', 'exchange': 'NSE'},
    {'symbol': 'DRREDDY', 'company_name': 'Dr. Reddy\'s Laboratories Ltd', 'market_cap': 600000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'CIPLA', 'company_name': 'Cipla Ltd', 'market_cap': 550000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'GRASIM', 'company_name': 'Grasim Industries Ltd', 'market_cap': 500000, 'sector': 'Textiles', 'exchange': 'NSE'},
    {'symbol': 'JSWSTEEL', 'company_name': 'JSW Steel Ltd', 'market_cap': 450000, 'sector': 'Steel', 'exchange': 'NSE'},
    {'symbol': 'TATAMOTORS', 'company_name': 'Tata Motors Ltd', 'market_cap': 400000, 'sector': 'Automobile', 'exchange': 'NSE'},
    {'symbol': 'BAJAJFINSV', 'company_name': 'Bajaj Finserv Ltd', 'market_cap': 350000, 'sector': 'NBFC', 'exchange': 'NSE'},
    {'symbol': 'ADANIPORTS', 'company_name': 'Adani Ports and Special Economic Zone Ltd', 'market_cap': 320000, 'sector': 'Infrastructure', 'exchange': 'NSE'},
    {'symbol': 'TATASTEEL', 'company_name': 'Tata Steel Ltd', 'market_cap': 300000, 'sector': 'Steel', 'exchange': 'NSE'},
    {'symbol': 'COALINDIA', 'company_name': 'Coal India Ltd', 'market_cap': 280000, 'sector': 'Mining', 'exchange': 'NSE'},
    {'symbol': 'INDUSINDBK', 'company_name': 'IndusInd Bank Ltd', 'market_cap': 260000, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'HEROMOTOCO', 'company_name': 'Hero MotoCorp Ltd', 'market_cap': 240000, 'sector': 'Automobile', 'exchange': 'NSE'},
    {'symbol': 'EICHERMOT', 'company_name': 'Eicher Motors Ltd', 'market_cap': 220000, 'sector': 'Automobile', 'exchange': 'NSE'},
    {'symbol': 'DIVISLAB', 'company_name': 'Divi\'s Laboratories Ltd', 'market_cap': 200000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'BRITANNIA', 'company_name': 'Britannia Industries Ltd', 'market_cap': 180000, 'sector': 'FMCG', 'exchange': 'NSE'},
    {'symbol': 'APOLLOHOSP', 'company_name': 'Apollo Hospitals Enterprise Ltd', 'market_cap': 160000, 'sector': 'Healthcare', 'exchange': 'NSE'},
    {'symbol': 'BAJAJHLDNG', 'company_name': 'Bajaj Holdings & Investment Ltd', 'market_cap': 140000, 'sector': 'Investment', 'exchange': 'NSE'},
    
    # Additional Large and Mid Cap Stocks
    {'symbol': 'M&M', 'company_name': 'Mahindra & Mahindra Ltd', 'market_cap': 120000, 'sector': 'Automobile', 'exchange': 'NSE'},
    {'symbol': 'HINDALCO', 'company_name': 'Hindalco Industries Ltd', 'market_cap': 100000, 'sector': 'Metals', 'exchange': 'NSE'},
    {'symbol': 'VEDL', 'company_name': 'Vedanta Ltd', 'market_cap': 90000, 'sector': 'Mining', 'exchange': 'NSE'},
    {'symbol': 'SHREECEM', 'company_name': 'Shree Cement Ltd', 'market_cap': 80000, 'sector': 'Cement', 'exchange': 'NSE'},
    {'symbol': 'DABUR', 'company_name': 'Dabur India Ltd', 'market_cap': 70000, 'sector': 'FMCG', 'exchange': 'NSE'},
    {'symbol': 'GODREJCP', 'company_name': 'Godrej Consumer Products Ltd', 'market_cap': 60000, 'sector': 'FMCG', 'exchange': 'NSE'},
    {'symbol': 'PIDILITIND', 'company_name': 'Pidilite Industries Ltd', 'market_cap': 55000, 'sector': 'Chemicals', 'exchange': 'NSE'},
    {'symbol': 'BIOCON', 'company_name': 'Biocon Ltd', 'market_cap': 50000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'MCDOWELL-N', 'company_name': 'United Spirits Ltd', 'market_cap': 45000, 'sector': 'Beverages', 'exchange': 'NSE'},
    {'symbol': 'COLPAL', 'company_name': 'Colgate Palmolive India Ltd', 'market_cap': 40000, 'sector': 'FMCG', 'exchange': 'NSE'},
    {'symbol': 'MARICO', 'company_name': 'Marico Ltd', 'market_cap': 35000, 'sector': 'FMCG', 'exchange': 'NSE'},
    {'symbol': 'MINDTREE', 'company_name': 'Mindtree Ltd', 'market_cap': 30000, 'sector': 'IT', 'exchange': 'NSE'},
    {'symbol': 'LUPIN', 'company_name': 'Lupin Ltd', 'market_cap': 28000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'CADILAHC', 'company_name': 'Cadila Healthcare Ltd', 'market_cap': 26000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'TORNTPHARM', 'company_name': 'Torrent Pharmaceuticals Ltd', 'market_cap': 24000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'AUROPHARMA', 'company_name': 'Aurobindo Pharma Ltd', 'market_cap': 22000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'GLENMARK', 'company_name': 'Glenmark Pharmaceuticals Ltd', 'market_cap': 20000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'PAGEIND', 'company_name': 'Page Industries Ltd', 'market_cap': 18000, 'sector': 'Textiles', 'exchange': 'NSE'},
    {'symbol': 'BERGEPAINT', 'company_name': 'Berger Paints India Ltd', 'market_cap': 16000, 'sector': 'Paints', 'exchange': 'NSE'},
    {'symbol': 'KANSAINER', 'company_name': 'Kansai Nerolac Paints Ltd', 'market_cap': 14000, 'sector': 'Paints', 'exchange': 'NSE'},
    {'symbol': 'AKZOINDIA', 'company_name': 'Akzo Nobel India Ltd', 'market_cap': 12000, 'sector': 'Paints', 'exchange': 'NSE'},
    {'symbol': '3MINDIA', 'company_name': '3M India Ltd', 'market_cap': 10000, 'sector': 'Diversified', 'exchange': 'NSE'},
    {'symbol': 'ABBOTINDIA', 'company_name': 'Abbott India Ltd', 'market_cap': 9000, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'ABB', 'company_name': 'ABB India Ltd', 'market_cap': 8000, 'sector': 'Engineering', 'exchange': 'NSE'},
    {'symbol': 'ADANIGREEN', 'company_name': 'Adani Green Energy Ltd', 'market_cap': 7000, 'sector': 'Power', 'exchange': 'NSE'},
    {'symbol': 'ADANITRANS', 'company_name': 'Adani Transmission Ltd', 'market_cap': 6000, 'sector': 'Power', 'exchange': 'NSE'},
    {'symbol': 'AMBUJACEM', 'company_name': 'Ambuja Cements Ltd', 'market_cap': 5000, 'sector': 'Cement', 'exchange': 'NSE'},
    {'symbol': 'BANDHANBNK', 'company_name': 'Bandhan Bank Ltd', 'market_cap': 4500, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'BATAINDIA', 'company_name': 'Bata India Ltd', 'market_cap': 4000, 'sector': 'Consumer Goods', 'exchange': 'NSE'},
    {'symbol': 'BHARATFORG', 'company_name': 'Bharat Forge Ltd', 'market_cap': 3500, 'sector': 'Engineering', 'exchange': 'NSE'},
    {'symbol': 'BOSCHLTD', 'company_name': 'Bosch Ltd', 'market_cap': 3000, 'sector': 'Engineering', 'exchange': 'NSE'},
    {'symbol': 'BPCL', 'company_name': 'Bharat Petroleum Corporation Ltd', 'market_cap': 2500, 'sector': 'Oil & Gas', 'exchange': 'NSE'},
    {'symbol': 'CHOLAFIN', 'company_name': 'Cholamandalam Investment and Finance Company Ltd', 'market_cap': 2000, 'sector': 'NBFC', 'exchange': 'NSE'},
    {'symbol': 'CROMPTON', 'company_name': 'Crompton Greaves Consumer Electricals Ltd', 'market_cap': 1800, 'sector': 'Consumer Goods', 'exchange': 'NSE'},
    {'symbol': 'DEEPAKFERT', 'company_name': 'Deepak Fertilisers and Petrochemicals Corporation Ltd', 'market_cap': 1600, 'sector': 'Chemicals', 'exchange': 'NSE'},
    {'symbol': 'DMART', 'company_name': 'Avenue Supermarts Ltd', 'market_cap': 1400, 'sector': 'Retail', 'exchange': 'NSE'},
    {'symbol': 'ESCORTS', 'company_name': 'Escorts Kubota Ltd', 'market_cap': 1200, 'sector': 'Engineering', 'exchange': 'NSE'},
    {'symbol': 'EXIDEIND', 'company_name': 'Exide Industries Ltd', 'market_cap': 1000, 'sector': 'Automobile', 'exchange': 'NSE'},
    {'symbol': 'FEDERALBNK', 'company_name': 'Federal Bank Ltd', 'market_cap': 900, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'GAIL', 'company_name': 'GAIL India Ltd', 'market_cap': 800, 'sector': 'Oil & Gas', 'exchange': 'NSE'},
    {'symbol': 'GODREJPROP', 'company_name': 'Godrej Properties Ltd', 'market_cap': 700, 'sector': 'Real Estate', 'exchange': 'NSE'},
    {'symbol': 'HAVELLS', 'company_name': 'Havells India Ltd', 'market_cap': 600, 'sector': 'Consumer Goods', 'exchange': 'NSE'},
    {'symbol': 'HDFCLIFE', 'company_name': 'HDFC Life Insurance Company Ltd', 'market_cap': 500, 'sector': 'Insurance', 'exchange': 'NSE'},
    {'symbol': 'ICICIGI', 'company_name': 'ICICI Lombard General Insurance Company Ltd', 'market_cap': 450, 'sector': 'Insurance', 'exchange': 'NSE'},
    {'symbol': 'IDBI', 'company_name': 'IDBI Bank Ltd', 'market_cap': 400, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'IDFCFIRSTB', 'company_name': 'IDFC First Bank Ltd', 'market_cap': 350, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'IGL', 'company_name': 'Indraprastha Gas Ltd', 'market_cap': 300, 'sector': 'Oil & Gas', 'exchange': 'NSE'},
    {'symbol': 'INDIGO', 'company_name': 'InterGlobe Aviation Ltd', 'market_cap': 250, 'sector': 'Aviation', 'exchange': 'NSE'},
    {'symbol': 'IRCTC', 'company_name': 'Indian Railway Catering and Tourism Corporation Ltd', 'market_cap': 200, 'sector': 'Services', 'exchange': 'NSE'},
    {'symbol': 'JINDALSTEL', 'company_name': 'Jindal Steel & Power Ltd', 'market_cap': 180, 'sector': 'Steel', 'exchange': 'NSE'},
    {'symbol': 'JUBLFOOD', 'company_name': 'Jubilant FoodWorks Ltd', 'market_cap': 160, 'sector': 'Food Services', 'exchange': 'NSE'},
    {'symbol': 'LICI', 'company_name': 'Life Insurance Corporation of India', 'market_cap': 140, 'sector': 'Insurance', 'exchange': 'NSE'},
    {'symbol': 'LALPATHLAB', 'company_name': 'Dr. Lal PathLabs Ltd', 'market_cap': 120, 'sector': 'Healthcare', 'exchange': 'NSE'},
    {'symbol': 'MCDOWELL-N', 'company_name': 'United Spirits Ltd', 'market_cap': 100, 'sector': 'Beverages', 'exchange': 'NSE'},
    {'symbol': 'METROPOLIS', 'company_name': 'Metropolis Healthcare Ltd', 'market_cap': 90, 'sector': 'Healthcare', 'exchange': 'NSE'},
    {'symbol': 'MFSL', 'company_name': 'Max Financial Services Ltd', 'market_cap': 80, 'sector': 'Financial Services', 'exchange': 'NSE'},
    {'symbol': 'MOTHERSON', 'company_name': 'Samvardhana Motherson International Ltd', 'market_cap': 70, 'sector': 'Automobile', 'exchange': 'NSE'},
    {'symbol': 'MPHASIS', 'company_name': 'Mphasis Ltd', 'market_cap': 60, 'sector': 'IT', 'exchange': 'NSE'},
    {'symbol': 'MRF', 'company_name': 'MRF Ltd', 'market_cap': 50, 'sector': 'Automobile', 'exchange': 'NSE'},
    {'symbol': 'MUTHOOTFIN', 'company_name': 'Muthoot Finance Ltd', 'market_cap': 45, 'sector': 'NBFC', 'exchange': 'NSE'},
    {'symbol': 'NAUKRI', 'company_name': 'Info Edge India Ltd', 'market_cap': 40, 'sector': 'IT', 'exchange': 'NSE'},
    {'symbol': 'NAVINFLUOR', 'company_name': 'Navin Fluorine International Ltd', 'market_cap': 35, 'sector': 'Chemicals', 'exchange': 'NSE'},
    {'symbol': 'NMDC', 'company_name': 'NMDC Ltd', 'market_cap': 30, 'sector': 'Mining', 'exchange': 'NSE'},
    {'symbol': 'OBEROI', 'company_name': 'Oberoi Realty Ltd', 'market_cap': 25, 'sector': 'Real Estate', 'exchange': 'NSE'},
    {'symbol': 'PEL', 'company_name': 'Piramal Enterprises Ltd', 'market_cap': 20, 'sector': 'Pharma', 'exchange': 'NSE'},
    {'symbol': 'PETRONET', 'company_name': 'Petronet LNG Ltd', 'market_cap': 18, 'sector': 'Oil & Gas', 'exchange': 'NSE'},
    {'symbol': 'PGHH', 'company_name': 'Procter & Gamble Hygiene and Health Care Ltd', 'market_cap': 16, 'sector': 'FMCG', 'exchange': 'NSE'},
    {'symbol': 'PNB', 'company_name': 'Punjab National Bank', 'market_cap': 14, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'POLYCAB', 'company_name': 'Polycab India Ltd', 'market_cap': 12, 'sector': 'Electricals', 'exchange': 'NSE'},
    {'symbol': 'PVR', 'company_name': 'PVR Ltd', 'market_cap': 10, 'sector': 'Entertainment', 'exchange': 'NSE'},
    {'symbol': 'RAMKY', 'company_name': 'Ramky Infrastructure Ltd', 'market_cap': 8, 'sector': 'Infrastructure', 'exchange': 'NSE'},
    {'symbol': 'RBLBANK', 'company_name': 'RBL Bank Ltd', 'market_cap': 6, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'RECLTD', 'company_name': 'REC Ltd', 'market_cap': 5, 'sector': 'Power', 'exchange': 'NSE'},
    {'symbol': 'SAIL', 'company_name': 'Steel Authority of India Ltd', 'market_cap': 4, 'sector': 'Steel', 'exchange': 'NSE'},
    {'symbol': 'SIEMENS', 'company_name': 'Siemens Ltd', 'market_cap': 3, 'sector': 'Engineering', 'exchange': 'NSE'},
    {'symbol': 'SRF', 'company_name': 'SRF Ltd', 'market_cap': 2, 'sector': 'Chemicals', 'exchange': 'NSE'},
    {'symbol': 'SUNTV', 'company_name': 'Sun TV Network Ltd', 'market_cap': 1, 'sector': 'Media', 'exchange': 'NSE'},
    {'symbol': 'TATACONSUM', 'company_name': 'Tata Consumer Products Ltd', 'market_cap': 0.8, 'sector': 'FMCG', 'exchange': 'NSE'},
    {'symbol': 'TATAPOWER', 'company_name': 'Tata Power Company Ltd', 'market_cap': 0.6, 'sector': 'Power', 'exchange': 'NSE'},
    {'symbol': 'TECHM', 'company_name': 'Tech Mahindra Ltd', 'market_cap': 0.4, 'sector': 'IT', 'exchange': 'NSE'},
    {'symbol': 'TORNTPOWER', 'company_name': 'Torrent Power Ltd', 'market_cap': 0.2, 'sector': 'Power', 'exchange': 'NSE'},
    {'symbol': 'TRENT', 'company_name': 'Trent Ltd', 'market_cap': 0.1, 'sector': 'Retail', 'exchange': 'NSE'},
    {'symbol': 'TVSMOTOR', 'company_name': 'TVS Motor Company Ltd', 'market_cap': 0.08, 'sector': 'Automobile', 'exchange': 'NSE'},
    {'symbol': 'UBL', 'company_name': 'United Breweries Ltd', 'market_cap': 0.06, 'sector': 'Beverages', 'exchange': 'NSE'},
    {'symbol': 'UPL', 'company_name': 'UPL Ltd', 'market_cap': 0.04, 'sector': 'Chemicals', 'exchange': 'NSE'},
    {'symbol': 'VEDL', 'company_name': 'Vedanta Ltd', 'market_cap': 0.02, 'sector': 'Mining', 'exchange': 'NSE'},
    {'symbol': 'VOLTAS', 'company_name': 'Voltas Ltd', 'market_cap': 0.01, 'sector': 'Consumer Goods', 'exchange': 'NSE'},
    {'symbol': 'WIPRO', 'company_name': 'Wipro Ltd', 'market_cap': 0.008, 'sector': 'IT', 'exchange': 'NSE'},
    {'symbol': 'YESBANK', 'company_name': 'Yes Bank Ltd', 'market_cap': 0.006, 'sector': 'Banking', 'exchange': 'NSE'},
    {'symbol': 'ZEEL', 'company_name': 'Zee Entertainment Enterprises Ltd', 'market_cap': 0.004, 'sector': 'Media', 'exchange': 'NSE'},
    {'symbol': 'ZOMATO', 'company_name': 'Zomato Ltd', 'market_cap': 0.002, 'sector': 'Food Services', 'exchange': 'NSE'},
]

# BSE Stocks - Major companies
BSE_STOCKS = [
    {'symbol': 'RELIANCE.BO', 'company_name': 'Reliance Industries Ltd', 'market_cap': 15000000, 'sector': 'Oil & Gas', 'exchange': 'BSE'},
    {'symbol': 'TCS.BO', 'company_name': 'Tata Consultancy Services Ltd', 'market_cap': 12000000, 'sector': 'IT', 'exchange': 'BSE'},
    {'symbol': 'HDFCBANK.BO', 'company_name': 'HDFC Bank Ltd', 'market_cap': 8000000, 'sector': 'Banking', 'exchange': 'BSE'},
    {'symbol': 'INFY.BO', 'company_name': 'Infosys Ltd', 'market_cap': 6000000, 'sector': 'IT', 'exchange': 'BSE'},
    {'symbol': 'HINDUNILVR.BO', 'company_name': 'Hindustan Unilever Ltd', 'market_cap': 5000000, 'sector': 'FMCG', 'exchange': 'BSE'},
    {'symbol': 'ITC.BO', 'company_name': 'ITC Ltd', 'market_cap': 4500000, 'sector': 'FMCG', 'exchange': 'BSE'},
    {'symbol': 'KOTAKBANK.BO', 'company_name': 'Kotak Mahindra Bank Ltd', 'market_cap': 4000000, 'sector': 'Banking', 'exchange': 'BSE'},
    {'symbol': 'BHARTIARTL.BO', 'company_name': 'Bharti Airtel Ltd', 'market_cap': 3800000, 'sector': 'Telecom', 'exchange': 'BSE'},
    {'symbol': 'SBIN.BO', 'company_name': 'State Bank of India', 'market_cap': 3500000, 'sector': 'Banking', 'exchange': 'BSE'},
    {'symbol': 'LT.BO', 'company_name': 'Larsen & Toubro Ltd', 'market_cap': 3200000, 'sector': 'Engineering', 'exchange': 'BSE'},
    {'symbol': 'ASIANPAINT.BO', 'company_name': 'Asian Paints Ltd', 'market_cap': 3000000, 'sector': 'Paints', 'exchange': 'BSE'},
    {'symbol': 'MARUTI.BO', 'company_name': 'Maruti Suzuki India Ltd', 'market_cap': 2800000, 'sector': 'Automobile', 'exchange': 'BSE'},
    {'symbol': 'AXISBANK.BO', 'company_name': 'Axis Bank Ltd', 'market_cap': 2600000, 'sector': 'Banking', 'exchange': 'BSE'},
    {'symbol': 'SUNPHARMA.BO', 'company_name': 'Sun Pharmaceutical Industries Ltd', 'market_cap': 2400000, 'sector': 'Pharma', 'exchange': 'BSE'},
    {'symbol': 'NESTLEIND.BO', 'company_name': 'Nestle India Ltd', 'market_cap': 2200000, 'sector': 'FMCG', 'exchange': 'BSE'},
    {'symbol': 'ULTRACEMCO.BO', 'company_name': 'UltraTech Cement Ltd', 'market_cap': 2000000, 'sector': 'Cement', 'exchange': 'BSE'},
    {'symbol': 'TITAN.BO', 'company_name': 'Titan Company Ltd', 'market_cap': 1800000, 'sector': 'Consumer Goods', 'exchange': 'BSE'},
    {'symbol': 'POWERGRID.BO', 'company_name': 'Power Grid Corporation of India Ltd', 'market_cap': 1600000, 'sector': 'Power', 'exchange': 'BSE'},
    {'symbol': 'NTPC.BO', 'company_name': 'NTPC Ltd', 'market_cap': 1400000, 'sector': 'Power', 'exchange': 'BSE'},
    {'symbol': 'ONGC.BO', 'company_name': 'Oil and Natural Gas Corporation Ltd', 'market_cap': 1200000, 'sector': 'Oil & Gas', 'exchange': 'BSE'},
]

def get_all_stocks():
    """Get combined list of all stocks"""
    return NSE_STOCKS + BSE_STOCKS

def get_nse_stocks():
    """Get NSE stocks"""
    return NSE_STOCKS

def get_bse_stocks():
    """Get BSE stocks"""
    return BSE_STOCKS

def get_top_stocks_by_market_cap(n=100):
    """Get top N stocks by market cap"""
    all_stocks = get_all_stocks()
    # Sort by market cap in descending order
    sorted_stocks = sorted(all_stocks, key=lambda x: x['market_cap'], reverse=True)
    return sorted_stocks[:n]
