# Streamlit Cloud Secrets Configuration
# This file should be used for local development only
# For Streamlit Cloud, set these as environment variables in the dashboard

[supabase]
url = "https://krlwufpvrdbehqwcngxi.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtybHd1ZnB2cmRiZWhxd2NuZ3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyODM0MTYsImV4cCI6MjA3Mjg1OTQxNn0.UQay88oKFRjwe3HjaCyW1CnyVOWwY2i7RU3Lx5uKx6o"
